global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: "auth-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['auth-service:19091']

  - job_name: "user-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:19092']

  - job_name: "coupon-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['coupon-service:19098']

  - job_name: 'limited-service-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19095' ]

  - job_name: 'product-service-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19093' ]

  - job_name: 'order-service-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19094' ]

  - job_name: 'auction-service-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:19097' ]